# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://ruifmaxx.github.io
date_format: "ordinal"
title: RuifMa
subtitle: "The world of RuifMa"
description: "The world of RuifMa"
keywords: RuifMa, 马瑞峰
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5
repository: RuifMaxx/RuifMaxx.github.io
# 对 css 和 js 资源的 cdn 加速配置
cdn:
    jsdelivr:
        enabled: true
# 组件配置
components:
    # 分享
    share:
        enabled: false
    # 不蒜子访问统计
    busuanzi:
        enabled: false
        start_date: 
# 压缩页面内容
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
# 文章字数统计
word_count:
    enabled: false
# 代码高亮风格，支持的 theme 列表见 https://github.com/mzlogin/rouge-themes
highlight_theme: github

# ---------------- #
#      Author      #
# ---------------- #
author: ruifmaxx
organization: 
organization_url: 
github_username: ruifmaxx
location: Jinan, China
email: ppeak@foxmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: Home

  -
    href: /categories/
    label: Categories

#   -
#     href: /archives/
#     label: Photograph

#   -
#     href: /open-source/
#     label: Cattery

#  -
#    href: /wiki/
#    label: Cat

  -
    href: /links/
    label: Downloads

  -
    href: /about/
    label: About

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: RuifMaxx
    repo: RuifMaxx.github.io
    oauth:
        client_id: dcdc31a6b9937ea077e1
        client_secret: b43211073717302d48c03d6182c374353268293a
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: RuifMaxx
    repo: RuifMaxx.github.io
    clientID: b380892a4589d9fcb945
    clientSecret: f6d67cd86cda26bd9138d867a4a6099cb1142bb9
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: true
    # 最多显示多少条搜索结果
    limit: 15

# ---------------- #
#      Google      #
# ---------------- #
google:
    analytics_id: 
    adsense:
        footer: false
        sidebar: false
        content_header: false
        content_footer: false
markdown: kramdown
