# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
#permalink:        pretty
#relative_permalinks: true

# Setup
title:            MAO
tagline:          'MAO的灵质空间'
description:      MAO的灵质空间
url:              ruifmaxx.github.io
baseurl:          /

collections:
  draft:
    output: true
  mao:
    output: true

author:
  name:           'MAO'
  url:            ppeak@foxmail.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ruifmaxx